version: "3"

services:
  chat:
    TODO
  directline:
    TODO
  dialog:
    TODO
  rasanlu:
    image: rasa/rasa_nlu:0.13.2-full
    container_name: meetup-rasa-nlu
    volumes:
      - "./rasa-data/projects:/app/projects"
      - "./rasa-data/logs:/app/logs"
    networks:
      - meetup
    ports:
      - 5000:5000
  nlu-trainer-app:
    image: ffauchille/nlu-trainer
    container_name: nlu-trainer-app
    networks:
      - meetup
    ports:
      - 8091:80
  nlu-trainer-api:
    image: ffauchille/nlu-trainer-api
    container_name: nlu-trainer-api
    networks:
      - meetup
    environment: 
      - MONGO_URI=mongodb://chatbot:chatbot@meetup-mongo:27017/?authSource=admin
      - MONGO_DB_NAME=nlutrainer
      - RASA_ENDPOINT=http://meetup-rasa-nlu:5000
    volumes:
      - "./api-data:/app/data"
    ports:
      - 8001:8000
  mongo:
    image: mongo:3.2
    restart: always
    container_name: meetup-mongo
    networks:
      - meetup
    environment:
      - MONGO_INITDB_ROOT_USERNAME=chatbot
      - MONGO_INITDB_ROOT_PASSWORD=chatbot
    expose:
      - 27017
    volumes:
      - "./data:/data/db"

networks:
  meetup:
    external:
      name: meetup